
# Syntax highlighting
markdown:            redcarpet
highlighter:         pygments

# Permalinks
permalink:           /:title
relative_permalinks: true

# Setup
timezone:            your timezone # eg. Asia/Kathmandu
locale:              your locale language # eg. en_us
name:				         site name
title:               site title
tagline:             'tagline'
description:         'description'
url:                 site url
rss:                 rss feed url
baseurl:             '/create-black-and-white-story-template'
baseurl_posts_img:   '/create-black-and-white-story-template/assets/images/posts/'
baseurl_featured_img: '/create-black-and-white-story-template/assets/images/hero/'
baseurl_featured_thumbnail: '/create-black-and-white-story-template/assets/images/thumbnail/'
baseurl_javascripts: '/create-black-and-white-story-template/assets/javascripts/'
icon:                your site icon path # /assets/img/icon.png [best 300px X 300px]
disqus:              disqus_shortname # get it on https://disqus.com/admin/

author:
  name:           	 your name
  url:            	 your site url
  facebook:          username
  twitter:           username
  google_plus:       username
  linkedin:          username
  dribbble:          username
  pinterest:         username
  kiva:              username

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
